### PR TITLE
chore(deps): upgrading passport-did-auth

### PR DESCRIPTION
**Pull request by artursudnik**
This PR:
- upgrades `passport-did-auth` to `v2.0.0-alpha.26`
- implements required adjustments to the code and CI settings

TODO:

- [ ] add `IPFS_PROJECTID` and `IPFS_PROJECTSECRET` secrets to the repository

### CODE REVIEW

**Comment by artursudnik** [comment]
@jrhender 
> Was there another place that you meant with the TODO?

Yes, values are provided for deployments, but they are also needed for CI GitHub worflow where they haven't been used so far.

**Comment by nichonien** [comment]
@jrhender @artursudnik Is there any specific requirement for which we want to update `passport-did-auth` in `did-auth-proxy`?

**Comment by artursudnik** [comment]
@nichonien Yes, `DEV` deployment triggers errors when using infura project id and secret.

**Comment by jrhender** [comment]
@nichonien I think it's also best to update passport-did-auth so that we upgrade to later versions more easily (e.g. that have security fixes)

**Comment by artursudnik** [comment]
@jrhender Now we have two instances of the E2E tests passing:
- for public IPFS gateway
- for authenticated API

**Review by jrhender — APPROVED** [review]
Looks good to me, thanks @artursudnik

**Pull request merged**
